#!/bin/sh

# set -x
# set -e

PREREQ="udev"
prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

[ -x /sbin/tailscaled ] || exit 0

# shellcheck disable=SC1091
. /scripts/functions

network_up()
{
    for conf in /run/net-*.conf /run/net6-*.conf; do
        if [ -e "$conf" ]; then
            # shellcheck disable=SC1090
            . "$conf"
            return 0
        fi
    done
    return 1
}

# shellcheck disable=SC3043
create_resolv_conf()
{
    if [ -e /etc/resolv.conf ]; then
        return
    fi

    local ns
    for ns in "${IPV4DNS0:-}" "${IPV4DNS1:-}" "${IPV6DNS0:-}" "${IPV6DNS1:-}"; do
        if [ -n "$ns" ] && [ "$ns" != "0.0.0.0" ]; then
            echo "nameserver $ns" >> /etc/resolv.conf
        fi
    done

    if [ -e /etc/resolv.conf ]; then
        return
    fi

    for ns in ${FALLBACK_DNS_SERVERS:-}; do
        if [ -n "$ns" ]; then
            echo "nameserver $ns" >> /etc/resolv.conf
        fi
    done
}

# shellcheck disable=SC2039,SC2086,SC3043
run_tailscale()
{
    # always run configure_networking() before tailscale(8); on NFS
    # mounts this has been done already
    [ "$BOOT" = nfs ] || configure_networking

    log_begin_msg "Starting tailscale"

    exec /sbin/tailscaled \
        --state=/var/lib/tailscale/tailscaled.state \
        --socket=/run/tailscale/tailscaled.sock \
        ${TAILSCALED_OPTIONS:-}
}

if [ -e /etc/tailscale/config ]; then
    # shellcheck disable=SC1091
    . /etc/tailscale/config
fi

modprobe tun

run_tailscale &
echo $! > "/run/tailscaled.pid"
