#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# shellcheck disable=SC1091
. /scripts/functions

EXE="$(readlink -f /sbin/tailscaled)" && [ -f "$EXE" ] || exit 1

if PID="$(cat /run/tailscaled.pid)" 2>/dev/null &&
        [ "$(readlink -f "/proc/$PID/exe")" = "$EXE" ]; then
    log_begin_msg "Stopping dropbear"

    /sbin/tailscaled -cleanup

    kill -TERM "$PID"
    log_end_msg
fi

IFDOWN="*"
if grep -q ^TAILSCALE_IFDOWN= /conf/initramfs.conf; then
    # XXX backward compatibility; remove once Stretch is the current stable
    # shellcheck disable=SC1091
    . /conf/initramfs.conf
    IFDOWN="$TAILSCALE_IFDOWN"
fi

if [ -e /etc/tailscale/config ]; then
    # shellcheck disable=SC1091
    . /etc/tailscale/config
fi

if [ "$BOOT" != nfs ] && [ "$IFDOWN" != none ]; then
    for IFACE in /sys/class/net/$IFDOWN; do
        [ -e "$IFACE" ] || continue
        IFACE="${IFACE#/sys/class/net/}"
        log_begin_msg "Bringing down $IFACE"
        ip link    set   dev "$IFACE" down
        ip address flush dev "$IFACE"
        ip route   flush dev "$IFACE"
        log_end_msg
    done
fi

exit 0
