#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/tailscaled sbin

copy_exec /bin/ip bin
copy_exec /usr/sbin/iptables sbin
copy_exec /usr/sbin/ip6tables sbin

copy_modules_dir kernel/net/ipv4/netfilter
copy_modules_dir kernel/net/ipv6/netfilter
copy_modules_dir kernel/net/netfilter
manual_add_modules tun

copy_file config /etc/ssl/certs/ca-certificates.crt

# Copy tailscale state
copy_file config /etc/tailscale/initramfs/tailscaled.state var/lib/tailscale/tailscaled.state

# Copy config
mkdir -p "$DESTDIR/etc/tailscale"
if [ -e /etc/tailscale/initramfs/config ]; then
    cp -p "/etc/tailscale/initramfs/config" "$DESTDIR/etc/tailscale/"
fi

# Create the home directory etc for the root user to enable ssh. This happens
# whether or not we requested tailscale ssh support at setup time, which is
# redundant, but we at least avoid doing it when dropbear-initramfs is present
# as it will prevent that from working.
if home=$(grep -s '^root:' "$DESTDIR/etc/passwd" | cut -d: -f6) && [ -n "$home" ]; then
    # Ensure /etc/passwd points at password stored in /etc/shadow
    sed -Ei -e 's/^root:[^:]+/root:x/' "$DESTDIR/etc/passwd"
else
   # create home
   home=$(mktemp -d "$DESTDIR/root-XXXXXX")
   chmod 0700 "$home"
   mkdir -m0700 "$home/.ssh"
   home=${home#"$DESTDIR"}
fi

#Create user/group required for login
for x in passwd group; do echo "$x: files"; done >"$DESTDIR/etc/nsswitch.conf"
echo "root:x:0:0:root:$home:/bin/sh" > "$DESTDIR/etc/passwd"
echo "root:!:19808:0:99999:7:::" >  "$DESTDIR/etc/shadow"
echo "root:x:0:" >"$DESTDIR/etc/group"

exit 0
